server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/order_db?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000&socketTimeoutMS=2000

spring.application.name=OrderService

inventory.base-url=http://localhost:8081